<a href="https://colab.research.google.com/github/Shavkatov-dev/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
print(pd.__version__)

2.2.2

In [5]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford"],
  'counts': [3, 7, 2]
}

df = pd.DataFrame(mydataset)

print(df)
print("=========")

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
=========

In [7]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ford", "BMW"],
  'counts': [3, 7, 2, 4, 5, 6]
}

df = pd.DataFrame(mydataset)

print(df)
print("=========")

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
3  Tesla       4
4   Ford       5
5    BMW       6
=========

In [8]:
df.head() # top-to-bottom (default 5 rows)

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
3  Tesla       4
4   Ford       5

In [9]:
df.head(8)

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
3  Tesla       4
4   Ford       5
5    BMW       6

In [11]:
df.tail(2) #bottom-to-top (default 5 rows)

   cars  counts
4  Ford       5
5   BMW       6

In [13]:
df.shape

(6, 2)

In [14]:
df.columns

Index(['cars', 'counts'], dtype='object')

In [16]:
df.dtypes

cars      object
counts     int64
dtype: object

In [17]:
print(df)

    cars  counts
0    BMW       3
1  Volvo       7
2   Ford       2
3  Tesla       4
4   Ford       5
5    BMW       6

In [19]:
df.describe(include="all") # numerical columns only

       cars    counts
count     6  6.000000
unique    4       NaN
top     BMW       NaN
freq      2       NaN
mean    NaN  4.500000
std     NaN  1.870829
min     NaN  2.000000
25%     NaN  3.250000
50%     NaN  4.500000
75%     NaN  5.750000
max     NaN  7.000000

In [23]:
df.iloc[1: 4] #row select

    cars  counts
1  Volvo       7
2   Ford       2
3  Tesla       4

In [26]:
df.loc[:, "counts"]

0    3
1    7
2    2
3    4
4    5
5    6
Name: counts, dtype: int64

In [28]:
df["counts"] > 3 #boolean

0    False
1     True
2    False
3     True
4     True
5     True
Name: counts, dtype: bool

In [31]:
df.mean(numeric_only=True)
df["counts"].mean[]

counts    4.5
dtype: float64

In [32]:
df.sum()

cars      BMWVolvoFordTeslaFordBMW
counts                          27
dtype: object

In [33]:
df.min()

cars      BMW
counts      2
dtype: object

In [34]:
df.max()

cars      Volvo
counts        7
dtype: object

In [35]:
df.median(numeric_only=True)

counts    4.5
dtype: float64

In [36]:
df.count()

cars      6
counts    6
dtype: int64

In [38]:
df.std(numeric_only=True)

counts    1.870829
dtype: float64

In [41]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None],
    "counts": [3, 7, None, 8, 1, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     NaN

In [43]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [47]:
df_missing.dropna(subset=["cars"])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [48]:
df_missing.fillna({"cars":"unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     0.0

In [51]:
df = pd.read_csv("Titanic-Dataset.csv")

df.tail(35)

#df = pd.rad_excel("Titanic-Dataset.xlsx")
#df = pd.read_json("Titanic-Dataset.xlsx")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
856,857,1,1,"Wick, Mrs. George Dennick (Mary Hitchcock)",female,45.0,1,1,36928,164.8667,NaN,S
857,858,1,1,"Daly, Mr. Peter Denis",male,51.0,0,0,113055,26.5500,E17,S
858,859,1,3,"Baclini, Mrs. Solomon (Latifa Qurban)",female,24.0,0,3,2666,19.2583,NaN,C
859,860,0,3,"Razi, Mr. Raihed",male,NaN,0,0,2629,7.2292,NaN,C
860,861,0,3,"Hansen, Mr. Claus Peter",male,41.0,2,0,350026,14.1083,NaN,S
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [52]:
df.to_excel("Output.xlsx")

In [55]:
df = pd.read_excel("Output.xlsx")
df.head()

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [56]:
# series => 1D

cars = pd.Series(["BMW", "Tesla", "None"])
print(cars)

0      BMW
1    Tesla
2     None
dtype: object

In [59]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None]